#!/usr/bin/env bash
exit_statuses=()
counter=0
gpu_number=1
gpu="--gpu $gpu_number"
epochs="--epochs all"
network_number_2="--network_number_2 3"
mode="--mode exp11_compare_linear_functions"
lr_schedule="--lr_schedule"
weight_decay="--weight_decay"
standard_arguments="$gpu $epochs $network_number $network_number_2 $mode $lr_schedule $weight_decay"












bash print_script_summary "${exit_statuses[@]}"

