#!/usr/bin/env bash
exit_statuses=()
counter=0
gpu_number=0
gpu="--gpu $gpu_number"
epochs="--epochs all"
mode="--mode exp11_compare_linear_functions"
extraction_type="--extraction_type linear"
lr_schedule="--lr_schedule"
weight_decay="--weight_decay"
standard_arguments="$gpu $epochs $network_number $network_number_2 $mode $lr_schedule $weight_decay" $extraction_type




data_set="--data_set MNIST"
network_type_coarse="--network_type_coarse MNIST"
network_type_fine="--network_type_fine FCN4"
architecture="$data_set $network_type_coarse $network_type_fine"
# EXPERIMENTS
counter=$((counter+1))
bash print_command $counter
python Experiments.py $standard_arguments $architecture --data_type 'training' --network_number '0' --network_number_1 '1'
exit_status=$?
bash print_summary $counter $exit_status $gpu_number
exit_statuses+=("$exit_status")

counter=$((counter+1))
bash print_command $counter
python Experiments.py $standard_arguments $architecture --data_type 'test' --network_number '0' --network_number_1 '1'
exit_status=$?
bash print_summary $counter $exit_status $gpu_number
exit_statuses+=("$exit_status")



bash print_script_summary "${exit_statuses[@]}"

