#!/usr/bin/env bash
exit_statuses=()
counter=0
main_directory="/home/martint/tropex/"
script_directory="${main_directory}Scripts/"
print_command="${script_directory}print_command"
print_summary="${script_directory}print_summary"
print_script_summary="${script_directory}print_script_summary"
tropex="${main_directory}Tropex.py"
experiments="${main_directory}Experiments.py"
gpu_number=0
gpu="--gpu $gpu_number"
epochs="--epochs all"
mode="--mode exp11_compare_linear_functions"
extraction_type="--extraction_type pos"
lr_schedule="--lr_schedule"
weight_decay="--weight_decay"
standard_arguments="$gpu $epochs $network_number $network_number_2 $mode $lr_schedule $weight_decay $extraction_type"


data_set="--data_set MNIST"
network_type_coarse="--network_type_coarse MNIST"
network_type_fine="--network_type_fine Convolutional"
architecture="$data_set $network_type_coarse $network_type_fine"
# EXPERIMENTS
counter=$((counter+1))
bash $print_command $counter
python $experiments $standard_arguments $architecture --data_type 'test' --network_number '0'
exit_status=$?
bash $print_summary $counter $exit_status $gpu_number
exit_statuses+=("$exit_status")


data_set="--data_set CIFAR10"
network_type_coarse="--network_type_coarse VGG"
network_type_fine="--network_type_fine Standard"
architecture="$data_set $network_type_coarse $network_type_fine"
# EXPERIMENTS
counter=$((counter+1))
bash $print_command $counter
python $experiments $standard_arguments $architecture --data_type 'test' --network_number '2'
exit_status=$?
bash $print_summary $counter $exit_status $gpu_number
exit_statuses+=("$exit_status")



bash $print_script_summary "${exit_statuses[@]}"

