#!/usr/bin/env bash

exit_statuses=("$@")
for t in ${!exit_statuses[@]};
	do if [ ${exit_statuses[$t]} -eq 0 ]; then
		echo "Command $((t+1)): Success."
	else
		echo "Command $((t+1)): Failure."
	fi
done

PARENT_COMMAND=$(ps -o command= -p "$PPID" | awk '{print $2}')
notify-send -i face-cool -u critical "Script finished." $PARENT_COMMAND

